---
title: "Project 3 Information"
format: html
---


## Overview

The amount, granularity, and quality of sports data has increased exponentially over the last two decades.
To draw insights and gain competitive advantages from these data, teams and leagues have invested heavily in building analytics departments.
Teams are increasingly looking for analysts with the ability to ask **and** answer substantively interesting sports questions. 
Identifying such analysts is complicated by at least two factors.
First, most undergraduate and graduate data science programs do not specifically train students to work with the types of data emerging in sports.
And second, most of the cutting-edge data is not publicly available, making it very difficult for aspiring analysts to demonstrat their ability to analyze that data.

Public data competitions have become an increasingly popular means of identifying talent in sports analytics.
Generally speaking, these competitions involve a team or league releasing a small amount of their data and inviting students and members of the public to answer substantively interesting questions using the data.
The earliest competitions were hackathons organized by the NBA in the mid-2010's[^nba].
By far the most prominent competition these days is the [NFL Big Data Bowl](https://operations.nfl.com/gameday/analytics/big-data-bowl/), an annual competition in which the NFL releases a small amount of its [Next Gen Stats](https://nextgenstats.nfl.com) and invites students and members of the public to use these data to draw new insight about the game.
Past competitions have resulted in new ways to

  * Predict where a running play will end based on initial player positions ([link](https://www.kaggle.com/competitions/nfl-big-data-bowl-2020/writeups/the-zoo-1st-place-solution-the-zoo))
  * Determine the optimal path for punt returners to follow ([link](https://www.nfl.com/videos/2022-big-data-bowl-robyn-ritchie-brendan-kumagai-ryker-moreau-elijah-cavan))
  * Grade pass-rushers ([link](https://www.kaggle.com/code/statsinthewild/strain-sacks-tackles-rushing-aggression-index))
  * Quantify the leverage created by offense when they use pre-snap motion ([link](https://www.kaggle.com/code/sshah30/cat-and-mouse-motion-vs-defensive-alignment/notebook))
  * Predict what might happen if the quarterback targeted a different receiver ([link](https://operations.nfl.com/media/3668/big-data-bowl-deshpande_evans.pdf))

Big Data Bowl finalists receive a cash prize and are given a chance to present their work at the NFL Combine in Indianapolis.
Over the last 9 years, over 50 people have been hired by professional teams and sports analytics companies based on their Big Data Bowl performance. 

[^nba]: See [this promotional video](https://www.youtube.com/watch?v=cWm9JgiluJ4) and read about some participants experiences [here](https://john-b-yang.github.io/nba-hack-17/) and [here](https://www.reddit.com/r/nba/comments/72dbzz/my_experience_at_the_nba_hackathon/).

<!--
Somewhat more recently, the Connecticut Sports Analytics Symposium began organizing an open data competition specifically targeted at undergraduate and graduate students.
Past competitions have involved
  * Determining the optimal rosters for the US Olympic gymnastics teams ([link](https://statds.org/events/ucsas2024/challenge.html))
  * Determining how batter swing speed and swing length are related to batter discipline and whether pitchers can "dictate" swings ([link](https://statds.org/events/csas2025/challenge.html))

In addition to presenting their work at the conference, past winners of the CSAS Data Challenge have been invited to share their finding with the US Olympic Committee. 

For the third project, I would like you work with data from either the [2027 NFL Big Data Bowl](https://operations.nfl.com/gameday/analytics/big-data-bowl/) or the [2026 CSAS Data Challenge](https://statds.org/events/csas2026/challenge.html).
My hope is that you develop your course projects into contest submissions; the submission deadlines are December 17, 2025 for the Big Data Bowl and January 17, 2026 for the CSAS Data Challenge.  
Details about both competitions and the relevant data is available below.
-->

For the third project, I would like you to work with data from the [2027 NFL Big Data Bowl](https://operations.nfl.com/gameday/analytics/big-data-bowl/).
The project report and recorded presentation are due on **Friday December 4 at 12:00pm (noon)**.

## Big Data Bowl


## Deliverables

The deliverables for Project 3 are the same as for Projects and 1 & 2 and carry similar requirements.

### Written Report

The written report consists of a non-technical executive summary and a technical report.
The executive summary, which should not exceed 500 words, should describe the overall goals, analytic approach, and main conclusions in non-technical language.
The executive summary should be free from jargon, code listings, figures, tables, and charts.
It should be written to be read and understood by a front office executive, coach, player, or fan with little data science experience.
The rest of written report should

  * Clearly state the problem being studied and provide sufficient background details and to motivate why the problem is important and interesting.
  * Describe the data and major steps of the analysis
  * Presents the main results within the context of the relevant sport(s) and supports the results with figures, tables, charts, and other statistical software output as appropriate.
  * Discusses the limitations of the analysis and outlines concrete steps for further development.

The technical section of the report should contain enough detail and code that another data scientist could replicate your analysis verify its soundness.
Code listings and output (e.g., figures, tables, charts, and numerical summaries) should be tightly integrated with the written exposition.
Here is a [good example of such integration](https://github.com/danmorse314/hockeyR-models).
Pay particular attention to the way the author complements the numerical results with detailed examples of individual performances. 

### Presentation

Each team will also record an 8--10 minute presentation (e.g., using Zoom) that provides an overview of their analysis.
Each presentation should include the following elements

  * Background (2--4 slides): clearly motivate and state the main problem being studied. Explain why it is interesting and important. Present just enough background to motivate the problem, while taking care not to overwhelm the audience with extraneous details. If appropriate, comment on the limitations of existing solutions to the problem or closely-related problems
  * Analysis overview (2--4 slides): present only the main steps of your analysis. Be sure to explain why each step was necessary and how these steps contribute to the overall solution. Focus more on the high-level ideas and motivation for each step rather than the specific implementation or software syntax
  * Main results (2--3 slides): distill your results into a few key points. Use figures, tables, charts, and other statistical software output to support your findings.
  * Conclusion (1 slide): briefly summarize your analysis and findings and outline between 1 and 3 specific directions for future development, improvement or refinement.
